#!/bin/bash

#SBATCH --job-name=array
#SBATCH --output=array_%A_%a.out
#SBATCH --error=array_%A_%a.err
#SBATCH --array=0-98
#SBATCH --time=40:00:00
#SBATCH --partition=shared
#SBATCH --ntasks=1
#SBATCH --mem=20G

# Print the task id.
echo "My SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID
cd $SLURM_SUBMIT_DIR
module load python/3.6.3
python3 /gpfs/home/ydong/workspace/mini/Minibatch_G.py $SLURM_ARRAY_TASK_ID
